-- AI Exam Grading App
-- PostgreSQL schema based on specs 01-04.

begin;

create table if not exists teachers (
  id bigint generated by default as identity primary key,
  teacher_code varchar(50) not null unique,
  full_name varchar(255) not null,
  email varchar(255) not null unique,
  username varchar(100) unique,
  password_hash text not null,
  status varchar(30) not null default 'active'
    check (status in ('active', 'locked', 'inactive')),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  created_by bigint references teachers(id) on update cascade on delete set null,
  updated_by bigint references teachers(id) on update cascade on delete set null
);

create table if not exists exams (
  id bigint generated by default as identity primary key,
  exam_code varchar(50) not null unique,
  version integer not null default 1 check (version > 0),
  title varchar(255) not null,
  description text,
  class_code varchar(50),
  subject_code varchar(50),
  subject_name varchar(255),
  exam_type varchar(50) not null,
  exam_round varchar(50),
  teacher_id bigint not null references teachers(id) on update cascade on delete restrict,
  question_file_path text,
  answer_file_path text,
  answer_extract jsonb,
  status varchar(30) not null default 'draft'
    check (status in ('draft', 'processing', 'ready', 'archived')),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  created_by bigint references teachers(id) on update cascade on delete set null,
  updated_by bigint references teachers(id) on update cascade on delete set null
);

alter table exams
  alter column answer_extract type jsonb
  using case
    when answer_extract is null then null
    when btrim(answer_extract::text) = '' then null
    when left(btrim(answer_extract::text), 1) in ('{', '[') then (answer_extract::text)::jsonb
    else to_jsonb(answer_extract::text)
  end;

create table if not exists submissions (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exams(id) on update cascade on delete cascade,
  student_code varchar(50) not null,
  student_name varchar(255) not null,
  class_code varchar(50) not null,
  subject_code varchar(50),
  submission_file_path text,
  submission_extract text,
  grading_result_file_path text,
  total_score numeric(5,2),
  max_score numeric(5,2),
  ai_confidence numeric(5,2),
  submitted_at timestamp not null default now(),
  graded_at timestamp,
  source_type varchar(30) not null default 'web'
    check (source_type in ('web', 'mobile', 'import')),
  status varchar(30) not null default 'uploaded'
    check (status in ('uploaded', 'extracting', 'extracted', 'grading', 'graded', 'published', 'failed')),
  published_at timestamp,
  reviewed_by bigint references teachers(id) on update cascade on delete set null,
  reviewed_at timestamp,
  review_status varchar(30) default 'recheck'
    check (review_status in ('approved', 'recheck', 'rejected')),
  notes text,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  created_by bigint references teachers(id) on update cascade on delete set null,
  updated_by bigint references teachers(id) on update cascade on delete set null,
  constraint submissions_total_score_chk check (total_score is null or total_score >= 0),
  constraint submissions_max_score_chk check (max_score is null or max_score > 0),
  constraint submissions_ai_confidence_chk check (ai_confidence is null or (ai_confidence >= 0 and ai_confidence <= 100))
);

create table if not exists system_logs (
  id bigint generated by default as identity primary key,
  log_type varchar(50) not null
    check (log_type in ('exam_extract', 'submission_extract', 'grading', 'publish', 'retry')),
  ref_table varchar(50) not null
    check (ref_table in ('exams', 'submissions')),
  ref_id bigint,
  exam_id bigint references exams(id) on update cascade on delete set null,
  submission_id bigint references submissions(id) on update cascade on delete set null,
  student_code varchar(50),
  student_name varchar(255),
  class_code varchar(50),
  workflow_execution_id varchar(100),
  model_name varchar(100),
  status varchar(30) not null
    check (status in ('queued', 'running', 'success', 'failed')),
  message text,
  request_payload jsonb,
  response_payload jsonb,
  error_message text,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  created_by bigint references teachers(id) on update cascade on delete set null,
  updated_by bigint references teachers(id) on update cascade on delete set null
);

commit;
