(function () {
  window.MockData = {
    teachers: [
      {
        id: "t-001",
        teacher_code: "GV001",
        full_name: "Trần Hà Linh",
        email: "teacher01@school.edu.vn",
        username: "teacher01",
        password: "Demo123",
        status: "active"
      }
    ],
    classOptions: ["12A1", "12A2", "11B1", "10C3"],
    subjectOptions: [
      { code: "MATH", name: "Toán học" },
      { code: "PHY", name: "Vật lý" },
      { code: "LIT", name: "Ngữ văn" },
      { code: "ENG", name: "Tiếng Anh" }
    ],
    exams: [
      {
        id: "e-001",
        exam_code: "EX-2026-001",
        version: 2,
        title: "Đề Toán giữa kỳ 2 - Lớp 12A1",
        description: "Trắc nghiệm 30 câu và 2 câu tự luận ngắn.",
        class_code: "12A1",
        subject_code: "MATH",
        subject_name: "Toán học",
        exam_type: "giua_ky",
        exam_round: "dot_1",
        teacher_id: "t-001",
        teacher_name: "Trần Hà Linh",
        question_file_path: "uploads/exams/toan-gk2-12a1.pdf",
        answer_file_path: "uploads/answers/toan-gk2-12a1-answer.pdf",
        answer_extract: "extract/exams/EX-2026-001-v2.json",
        status: "ready",
        created_at: "2026-04-10 08:30",
        updated_at: "2026-04-13 14:05"
      },
      {
        id: "e-002",
        exam_code: "EX-2026-002",
        version: 1,
        title: "Đề Ngữ văn 15 phút - Lớp 11B1",
        description: "Đọc hiểu và viết đoạn ngắn.",
        class_code: "11B1",
        subject_code: "LIT",
        subject_name: "Ngữ văn",
        exam_type: "15p",
        exam_round: "dot_2",
        teacher_id: "t-001",
        teacher_name: "Trần Hà Linh",
        question_file_path: "uploads/exams/van-15p-11b1.docx",
        answer_file_path: "uploads/answers/van-15p-11b1-answer.docx",
        answer_extract: "extract/exams/EX-2026-002-v1.json",
        status: "processing",
        created_at: "2026-04-15 10:00",
        updated_at: "2026-04-15 10:15"
      },
      {
        id: "e-003",
        exam_code: "EX-2026-003",
        version: 1,
        title: "Đề Tiếng Anh cuối kỳ - Lớp 12A2",
        description: "Nghe, đọc và viết.",
        class_code: "12A2",
        subject_code: "ENG",
        subject_name: "Tiếng Anh",
        exam_type: "cuoi_ky",
        exam_round: "dot_1",
        teacher_id: "t-001",
        teacher_name: "Trần Hà Linh",
        question_file_path: "uploads/exams/eng-final-12a2.pdf",
        answer_file_path: "uploads/answers/eng-final-12a2.pdf",
        answer_extract: "extract/exams/EX-2026-003-v1.json",
        status: "draft",
        created_at: "2026-04-17 09:20",
        updated_at: "2026-04-17 09:20"
      }
    ],
    submissions: [
      {
        id: "s-001",
        exam_id: "e-001",
        student_code: "SV2026001",
        student_name: "Nguyễn Minh An",
        class_code: "12A1",
        subject_code: "MATH",
        subject_name: "Toán học",
        exam_title: "Đề Toán giữa kỳ 2 - Lớp 12A1",
        exam_type: "giua_ky",
        exam_round: "dot_1",
        submission_file_path: "uploads/submissions/SV2026001-math.pdf",
        submission_extract: "extract/submissions/SV2026001.json",
        grading_result_file_path: "grading/SV2026001-result.json",
        total_score: 8.5,
        max_score: 10,
        ai_confidence: 96,
        submitted_at: "2026-04-14 09:05",
        graded_at: "2026-04-14 09:09",
        source_type: "web",
        status: "published",
        published_at: "2026-04-14 09:30",
        review_status: "approved",
        reviewed_by: "t-001",
        reviewed_at: "2026-04-14 09:28",
        notes: "Làm đúng phần lớn câu trắc nghiệm.",
        questions: [
          {
            no: 1,
            type: "trac_nghiem",
            question: "Đạo hàm của f(x) = x^2 là gì?",
            student_answer: "2x",
            correct_answer: "2x",
            result: "Dung",
            score: 1,
            explanation: "Đạo hàm cơ bản đúng theo quy tắc lũy thừa."
          },
          {
            no: 2,
            type: "trac_nghiem",
            question: "Giá trị của sin(30 độ)?",
            student_answer: "1/2",
            correct_answer: "1/2",
            result: "Dung",
            score: 1,
            explanation: "Đúng giá trị lượng giác cơ bản."
          },
          {
            no: 3,
            type: "tu_luan",
            question: "Giải phương trình x^2 - 5x + 6 = 0",
            student_answer: "x = 2 hoặc x = 3",
            correct_answer: "x = 2, x = 3",
            result: "Dung",
            score: 2.5,
            explanation: "Lập luận đúng và kết quả đầy đủ."
          },
          {
            no: 4,
            type: "tu_luan",
            question: "Tìm GTLN của hàm số trên đoạn [0,2]",
            student_answer: "GTLN = 5 tai x = 2",
            correct_answer: "GTLN = 6 tai x = 2",
            result: "Sai",
            score: 1,
            explanation: "Cách làm hợp lý nhưng tính toán cuối cùng sai."
          }
        ]
      },
      {
        id: "s-002",
        exam_id: "e-001",
        student_code: "SV2026002",
        student_name: "Lê Thu Trang",
        class_code: "12A1",
        subject_code: "MATH",
        subject_name: "Toán học",
        exam_title: "Đề Toán giữa kỳ 2 - Lớp 12A1",
        exam_type: "giua_ky",
        exam_round: "dot_1",
        submission_file_path: "uploads/submissions/SV2026002-math.pdf",
        submission_extract: "extract/submissions/SV2026002.json",
        grading_result_file_path: "grading/SV2026002-result.json",
        total_score: 6.75,
        max_score: 10,
        ai_confidence: 88,
        submitted_at: "2026-04-14 09:08",
        graded_at: "2026-04-14 09:12",
        source_type: "web",
        status: "graded",
        published_at: "",
        review_status: "recheck",
        reviewed_by: "",
        reviewed_at: "",
        notes: "Cần giáo viên xem lại 1 câu tự luận.",
        questions: [
          {
            no: 1,
            type: "trac_nghiem",
            question: "Đạo hàm của f(x) = x^2 là gì?",
            student_answer: "x",
            correct_answer: "2x",
            result: "Sai",
            score: 0,
            explanation: "Sai công thức đạo hàm."
          },
          {
            no: 2,
            type: "trac_nghiem",
            question: "Giá trị của sin(30 độ)?",
            student_answer: "1/2",
            correct_answer: "1/2",
            result: "Dung",
            score: 1,
            explanation: "Trả lời đúng."
          },
          {
            no: 3,
            type: "tu_luan",
            question: "Giải phương trình x^2 - 5x + 6 = 0",
            student_answer: "x = 2 va x = 3",
            correct_answer: "x = 2, x = 3",
            result: "Dung",
            score: 2.5,
            explanation: "Đúng ý và đầy đủ bước chính."
          },
          {
            no: 4,
            type: "tu_luan",
            question: "Tìm GTLN của hàm số trên đoạn [0,2]",
            student_answer: "Không rõ kết quả cuối",
            correct_answer: "GTLN = 6 tai x = 2",
            result: "Sai",
            score: 0.75,
            explanation: "Có hướng làm nhưng thiếu kết luận, điểm chỉ được một phần."
          }
        ]
      },
      {
        id: "s-003",
        exam_id: "e-002",
        student_code: "SV2026105",
        student_name: "Phạm Gia Bảo",
        class_code: "11B1",
        subject_code: "LIT",
        subject_name: "Ngữ văn",
        exam_title: "Đề Ngữ văn 15 phút - Lớp 11B1",
        exam_type: "15p",
        exam_round: "dot_2",
        submission_file_path: "uploads/submissions/SV2026105-van.docx",
        submission_extract: "extract/submissions/SV2026105.json",
        grading_result_file_path: "grading/SV2026105-result.json",
        total_score: 0,
        max_score: 10,
        ai_confidence: 0,
        submitted_at: "2026-04-16 08:10",
        graded_at: "",
        source_type: "web",
        status: "failed",
        published_at: "",
        review_status: "rejected",
        reviewed_by: "",
        reviewed_at: "",
        notes: "OCR lỗi tại trang 2.",
        questions: []
      }
    ],
    logs: [
      {
        id: "l-001",
        log_type: "exam_extract",
        ref_table: "exams",
        ref_id: "e-001",
        exam_id: "e-001",
        submission_id: "",
        exam_code: "EX-2026-001",
        student_code: "",
        student_name: "",
        class_code: "12A1",
        workflow_execution_id: "wf-extract-exam-001",
        model_name: "gpt-4.1-mini",
        status: "success",
        message: "Trích xuất đáp án thành công.",
        request_payload: "{ format: 'pdf', version: 2 }",
        response_payload: "{ pages: 6, questions: 32 }",
        error_message: "",
        created_at: "2026-04-13 14:02"
      },
      {
        id: "l-002",
        log_type: "grading",
        ref_table: "submissions",
        ref_id: "s-001",
        exam_id: "e-001",
        submission_id: "s-001",
        exam_code: "EX-2026-001",
        student_code: "SV2026001",
        student_name: "Nguyễn Minh An",
        class_code: "12A1",
        workflow_execution_id: "wf-grade-001",
        model_name: "gpt-5.4",
        status: "success",
        message: "Chấm điểm thành công, độ tin cậy cao.",
        request_payload: "{ question_count: 4, submission: 's-001' }",
        response_payload: "{ total_score: 8.5, confidence: 96 }",
        error_message: "",
        created_at: "2026-04-14 09:09"
      },
      {
        id: "l-003",
        log_type: "submission_extract",
        ref_table: "submissions",
        ref_id: "s-003",
        exam_id: "e-002",
        submission_id: "s-003",
        exam_code: "EX-2026-002",
        student_code: "SV2026105",
        student_name: "Phạm Gia Bảo",
        class_code: "11B1",
        workflow_execution_id: "wf-submission-extract-009",
        model_name: "ocr-engine-v2",
        status: "failed",
        message: "Không đọc được trang 2 của file bài nộp.",
        request_payload: "{ file: 'SV2026105-van.docx' }",
        response_payload: "{}",
        error_message: "Unsupported embedded image format.",
        created_at: "2026-04-16 08:15"
      },
      {
        id: "l-004",
        log_type: "publish",
        ref_table: "submissions",
        ref_id: "s-001",
        exam_id: "e-001",
        submission_id: "s-001",
        exam_code: "EX-2026-001",
        student_code: "SV2026001",
        student_name: "Nguyễn Minh An",
        class_code: "12A1",
        workflow_execution_id: "wf-publish-001",
        model_name: "",
        status: "success",
        message: "Đã công bố kết quả cho sinh viên.",
        request_payload: "{ submission: 's-001' }",
        response_payload: "{ published: true }",
        error_message: "",
        created_at: "2026-04-14 09:30"
      }
    ]
  };
})();