(function () {
  window.MockData = {
    teachers: [
      {
        id: "t-001",
        teacher_code: "GV001",
        full_name: "Tran Ha Linh",
        email: "teacher01@school.edu.vn",
        username: "teacher01",
        password: "Demo123",
        status: "active"
      }
    ],
    classOptions: ["12A1", "12A2", "11B1", "10C3"],
    subjectOptions: [
      { code: "MATH", name: "Toan hoc" },
      { code: "PHY", name: "Vat ly" },
      { code: "LIT", name: "Ngu van" },
      { code: "ENG", name: "Tieng Anh" }
    ],
    exams: [
      {
        id: "e-001",
        exam_code: "EX-2026-001",
        version: 2,
        title: "De Toan giua ky 2 - Lop 12A1",
        description: "Trac nghiem 30 cau va 2 cau tu luan ngan.",
        class_code: "12A1",
        subject_code: "MATH",
        subject_name: "Toan hoc",
        exam_type: "giua_ky",
        exam_round: "dot_1",
        teacher_id: "t-001",
        teacher_name: "Tran Ha Linh",
        question_file_path: "uploads/exams/toan-gk2-12a1.pdf",
        answer_file_path: "uploads/answers/toan-gk2-12a1-answer.pdf",
        answer_extract_file_path: "extract/exams/EX-2026-001-v2.json",
        status: "ready",
        created_at: "2026-04-10 08:30",
        updated_at: "2026-04-13 14:05"
      },
      {
        id: "e-002",
        exam_code: "EX-2026-002",
        version: 1,
        title: "De Ngu van 15 phut - Lop 11B1",
        description: "Doc hieu va viet doan ngan.",
        class_code: "11B1",
        subject_code: "LIT",
        subject_name: "Ngu van",
        exam_type: "15p",
        exam_round: "dot_2",
        teacher_id: "t-001",
        teacher_name: "Tran Ha Linh",
        question_file_path: "uploads/exams/van-15p-11b1.docx",
        answer_file_path: "uploads/answers/van-15p-11b1-answer.docx",
        answer_extract_file_path: "extract/exams/EX-2026-002-v1.json",
        status: "processing",
        created_at: "2026-04-15 10:00",
        updated_at: "2026-04-15 10:15"
      },
      {
        id: "e-003",
        exam_code: "EX-2026-003",
        version: 1,
        title: "De Tieng Anh cuoi ky - Lop 12A2",
        description: "Nghe, doc va viet.",
        class_code: "12A2",
        subject_code: "ENG",
        subject_name: "Tieng Anh",
        exam_type: "cuoi_ky",
        exam_round: "dot_1",
        teacher_id: "t-001",
        teacher_name: "Tran Ha Linh",
        question_file_path: "uploads/exams/eng-final-12a2.pdf",
        answer_file_path: "uploads/answers/eng-final-12a2.pdf",
        answer_extract_file_path: "extract/exams/EX-2026-003-v1.json",
        status: "draft",
        created_at: "2026-04-17 09:20",
        updated_at: "2026-04-17 09:20"
      }
    ],
    submissions: [
      {
        id: "s-001",
        exam_id: "e-001",
        student_code: "SV2026001",
        student_name: "Nguyen Minh An",
        class_code: "12A1",
        subject_code: "MATH",
        subject_name: "Toan hoc",
        exam_title: "De Toan giua ky 2 - Lop 12A1",
        exam_type: "giua_ky",
        exam_round: "dot_1",
        submission_file_path: "uploads/submissions/SV2026001-math.pdf",
        submission_extract_file_path: "extract/submissions/SV2026001.json",
        grading_result_file_path: "grading/SV2026001-result.json",
        total_score: 8.5,
        max_score: 10,
        ai_confidence: 96,
        submitted_at: "2026-04-14 09:05",
        graded_at: "2026-04-14 09:09",
        source_type: "web",
        status: "published",
        published_at: "2026-04-14 09:30",
        review_status: "approved",
        reviewed_by: "t-001",
        reviewed_at: "2026-04-14 09:28",
        notes: "Lam dung phan lon cau trac nghiem.",
        questions: [
          {
            no: 1,
            type: "trac_nghiem",
            question: "Dao ham cua f(x) = x^2 la gi?",
            student_answer: "2x",
            correct_answer: "2x",
            result: "Dung",
            score: 1,
            explanation: "Dao ham co ban dung theo quy tac luy thua."
          },
          {
            no: 2,
            type: "trac_nghiem",
            question: "Gia tri cua sin(30 do)?",
            student_answer: "1/2",
            correct_answer: "1/2",
            result: "Dung",
            score: 1,
            explanation: "Dung gia tri luong giac co ban."
          },
          {
            no: 3,
            type: "tu_luan",
            question: "Giai phuong trinh x^2 - 5x + 6 = 0",
            student_answer: "x = 2 hoac x = 3",
            correct_answer: "x = 2, x = 3",
            result: "Dung",
            score: 2.5,
            explanation: "Lap luan dung va ket qua day du."
          },
          {
            no: 4,
            type: "tu_luan",
            question: "Tim GTLN cua ham so tren doan [0,2]",
            student_answer: "GTLN = 5 tai x = 2",
            correct_answer: "GTLN = 6 tai x = 2",
            result: "Sai",
            score: 1,
            explanation: "Cach lam hop ly nhung tinh toan cuoi cung sai."
          }
        ]
      },
      {
        id: "s-002",
        exam_id: "e-001",
        student_code: "SV2026002",
        student_name: "Le Thu Trang",
        class_code: "12A1",
        subject_code: "MATH",
        subject_name: "Toan hoc",
        exam_title: "De Toan giua ky 2 - Lop 12A1",
        exam_type: "giua_ky",
        exam_round: "dot_1",
        submission_file_path: "uploads/submissions/SV2026002-math.pdf",
        submission_extract_file_path: "extract/submissions/SV2026002.json",
        grading_result_file_path: "grading/SV2026002-result.json",
        total_score: 6.75,
        max_score: 10,
        ai_confidence: 88,
        submitted_at: "2026-04-14 09:08",
        graded_at: "2026-04-14 09:12",
        source_type: "web",
        status: "graded",
        published_at: "",
        review_status: "recheck",
        reviewed_by: "",
        reviewed_at: "",
        notes: "Can giao vien xem lai 1 cau tu luan.",
        questions: [
          {
            no: 1,
            type: "trac_nghiem",
            question: "Dao ham cua f(x) = x^2 la gi?",
            student_answer: "x",
            correct_answer: "2x",
            result: "Sai",
            score: 0,
            explanation: "Sai cong thuc dao ham."
          },
          {
            no: 2,
            type: "trac_nghiem",
            question: "Gia tri cua sin(30 do)?",
            student_answer: "1/2",
            correct_answer: "1/2",
            result: "Dung",
            score: 1,
            explanation: "Tra loi dung."
          },
          {
            no: 3,
            type: "tu_luan",
            question: "Giai phuong trinh x^2 - 5x + 6 = 0",
            student_answer: "x = 2 va x = 3",
            correct_answer: "x = 2, x = 3",
            result: "Dung",
            score: 2.5,
            explanation: "Dung y va day du buoc chinh."
          },
          {
            no: 4,
            type: "tu_luan",
            question: "Tim GTLN cua ham so tren doan [0,2]",
            student_answer: "Khong ro ket qua cuoi",
            correct_answer: "GTLN = 6 tai x = 2",
            result: "Sai",
            score: 0.75,
            explanation: "Co huong lam nhung thieu ket luan, diem chi duoc mot phan."
          }
        ]
      },
      {
        id: "s-003",
        exam_id: "e-002",
        student_code: "SV2026105",
        student_name: "Pham Gia Bao",
        class_code: "11B1",
        subject_code: "LIT",
        subject_name: "Ngu van",
        exam_title: "De Ngu van 15 phut - Lop 11B1",
        exam_type: "15p",
        exam_round: "dot_2",
        submission_file_path: "uploads/submissions/SV2026105-van.docx",
        submission_extract_file_path: "extract/submissions/SV2026105.json",
        grading_result_file_path: "grading/SV2026105-result.json",
        total_score: 0,
        max_score: 10,
        ai_confidence: 0,
        submitted_at: "2026-04-16 08:10",
        graded_at: "",
        source_type: "web",
        status: "failed",
        published_at: "",
        review_status: "rejected",
        reviewed_by: "",
        reviewed_at: "",
        notes: "OCR loi tai trang 2.",
        questions: []
      }
    ],
    logs: [
      {
        id: "l-001",
        log_type: "exam_extract",
        ref_table: "exams",
        ref_id: "e-001",
        exam_id: "e-001",
        submission_id: "",
        exam_code: "EX-2026-001",
        student_code: "",
        student_name: "",
        class_code: "12A1",
        workflow_execution_id: "wf-extract-exam-001",
        model_name: "gpt-4.1-mini",
        status: "success",
        message: "Extract dap an thanh cong.",
        request_payload: "{ format: 'pdf', version: 2 }",
        response_payload: "{ pages: 6, questions: 32 }",
        error_message: "",
        created_at: "2026-04-13 14:02"
      },
      {
        id: "l-002",
        log_type: "grading",
        ref_table: "submissions",
        ref_id: "s-001",
        exam_id: "e-001",
        submission_id: "s-001",
        exam_code: "EX-2026-001",
        student_code: "SV2026001",
        student_name: "Nguyen Minh An",
        class_code: "12A1",
        workflow_execution_id: "wf-grade-001",
        model_name: "gpt-5.4",
        status: "success",
        message: "Cham diem thanh cong, do tin cay cao.",
        request_payload: "{ question_count: 4, submission: 's-001' }",
        response_payload: "{ total_score: 8.5, confidence: 96 }",
        error_message: "",
        created_at: "2026-04-14 09:09"
      },
      {
        id: "l-003",
        log_type: "submission_extract",
        ref_table: "submissions",
        ref_id: "s-003",
        exam_id: "e-002",
        submission_id: "s-003",
        exam_code: "EX-2026-002",
        student_code: "SV2026105",
        student_name: "Pham Gia Bao",
        class_code: "11B1",
        workflow_execution_id: "wf-submission-extract-009",
        model_name: "ocr-engine-v2",
        status: "failed",
        message: "Khong doc duoc trang 2 cua file bai nop.",
        request_payload: "{ file: 'SV2026105-van.docx' }",
        response_payload: "{}",
        error_message: "Unsupported embedded image format.",
        created_at: "2026-04-16 08:15"
      },
      {
        id: "l-004",
        log_type: "publish",
        ref_table: "submissions",
        ref_id: "s-001",
        exam_id: "e-001",
        submission_id: "s-001",
        exam_code: "EX-2026-001",
        student_code: "SV2026001",
        student_name: "Nguyen Minh An",
        class_code: "12A1",
        workflow_execution_id: "wf-publish-001",
        model_name: "",
        status: "success",
        message: "Da cong bo ket qua cho sinh vien.",
        request_payload: "{ submission: 's-001' }",
        response_payload: "{ published: true }",
        error_message: "",
        created_at: "2026-04-14 09:30"
      }
    ]
  };
})();